name: python_spatial
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - matplotlib
  - nbclient
  - nbformat
  - papermill
  - numpy
  - pandas
  - pyyaml
  - python-igraph
  - leidenalg
  - cuda-version=12.9
  - cuml=26.04
  - cuvs=26.04
  - cugraph=26.04
  - scikit-learn>=1.6,<1.7
  - pytorch-gpu
  - torchvision
  - scanpy
  - session-info
  - spatialdata
  - spatialdata-io
  - spatialdata-plot
  - squidpy
  - pip:
    - scikit-learn>=1.6,<1.7
    - rapids-singlecell-cu12==0.15.2
    - cellpose
    - seaborn
    - plotly
    - gseapy
    - opencv-python-headless
    - matplotlib-scalebar
    - matplotlib-venn
    - session-info2
    - dask-image
    - segment-anything
    - omnipath
