name: python_spatial
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - matplotlib
  - nbclient
  - nbformat
  - papermill
  - numpy
  - pandas
  - pyyaml
  - python-igraph
  - leidenalg
  - cuda-version=12.5
  - pip:
    - rapids-singlecell
  - scanpy
  - session-info
  - spatialdata
  - spatialdata-io
  - spatialdata-plot
  - squidpy
