name: base
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12.4
  - squidpy=1.6.1
  - spatialdata=0.2.5
  - spatialdata-io=0.1.5
  - spatialdata-plot=0.2.7
  - scanpy=1.10.3
  - anndata=0.10.9
  - pandas=2.2.3
  - numpy=1.26.4
  - scipy=1.14.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - geopandas=1.0.1
  - shapely=2.0.6
